apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: verda-flask-dev
resources:
  - ../../base
images:
  - name: harbor.95.133.253.118.sslip.io/verda-harbor/verda-flask
    newTag: v1
commonLabels:
  environment: dev
